import { ProductionPlan } from "@/lib/types";
import {
  TrendingUp,
  Factory,
  Clock,
  Target,
  AlertTriangle,
  DollarSign,
  CheckCircle,
  AlertCircle,
  Calendar,
} from "lucide-react";

export const PRODUCTION_PLANS: ProductionPlan[] = [
  {
    id: "1",
    planName: "Q1 Production Batch",
    description: "First quarter production planning",
    startDate: "2024-01-15",
    endDate: "2024-03-31",
    products: [
      {
        productId: "1",
        productName: "Premium Floor Cleaner",
        quantityKg: 500,
        costPerKg: 27.22,
        totalCost: 13610,
        materialsRequired: [
          {
            materialId: "6",
            materialName: "NaCl",
            requiredQty: 175,
            availableQty: 200,
            shortage: 0,
            costPerKg: 6,
            totalCost: 1050,
            unit: "kg",
          },
          {
            materialId: "8",
            materialName: "Soda Ash",
            requiredQty: 110,
            availableQty: 80,
            shortage: 30,
            costPerKg: 40.95,
            totalCost: 4504.5,
            unit: "kg",
          },
          {
            materialId: "7",
            materialName: "Dolamite",
            requiredQty: 125,
            availableQty: 150,
            shortage: 0,
            costPerKg: 5.25,
            totalCost: 656.25,
            unit: "kg",
          },
          {
            materialId: "2",
            materialName: "Acid Slurry 90%",
            requiredQty: 40,
            availableQty: 50,
            shortage: 0,
            costPerKg: 122.85,
            totalCost: 4914,
            unit: "kg",
          },
          {
            materialId: "4",
            materialName: "Caustic Soda",
            requiredQty: 9,
            availableQty: 25,
            shortage: 0,
            costPerKg: 59.85,
            totalCost: 538.65,
            unit: "kg",
          },
          {
            materialId: "9",
            materialName: "AOS Powder 96%",
            requiredQty: 12.5,
            availableQty: 20,
            shortage: 0,
            costPerKg: 155.4,
            totalCost: 1942.5,
            unit: "kg",
          },
        ],
      },
      {
        productId: "2",
        productName: "Bathroom Cleaner Pro",
        quantityKg: 300,
        costPerKg: 34.06,
        totalCost: 10218,
        materialsRequired: [
          {
            materialId: "5",
            materialName: "Citric Acid",
            requiredQty: 45,
            availableQty: 60,
            shortage: 0,
            costPerKg: 97.65,
            totalCost: 4394.25,
            unit: "kg",
          },
          {
            materialId: "4",
            materialName: "Caustic Soda",
            requiredQty: 15,
            availableQty: 25,
            shortage: 0,
            costPerKg: 59.85,
            totalCost: 897.75,
            unit: "kg",
          },
          {
            materialId: "2",
            materialName: "Acid Slurry 90%",
            requiredQty: 36,
            availableQty: 50,
            shortage: 0,
            costPerKg: 122.85,
            totalCost: 4422.6,
            unit: "kg",
          },
          {
            materialId: "1",
            materialName: "Acid Blue Color",
            requiredQty: 0.3,
            availableQty: 5,
            shortage: 0,
            costPerKg: 1680,
            totalCost: 504,
            unit: "kg",
          },
        ],
      },
    ],
    totalCost: 23828,
    totalRevenue: 38500,
    totalProfit: 14672,
    status: "in-progress",
    progress: 65,
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    planName: "Special Order Batch",
    description: "Custom order for large client",
    startDate: "2024-02-01",
    endDate: "2024-02-15",
    products: [
      {
        productId: "3",
        productName: "Glass Cleaner",
        quantityKg: 200,
        costPerKg: 22.15,
        totalCost: 4430,
        materialsRequired: [
          {
            materialId: "2",
            materialName: "Acid Slurry 90%",
            requiredQty: 20,
            availableQty: 50,
            shortage: 0,
            costPerKg: 122.85,
            totalCost: 2457,
            unit: "kg",
          },
          {
            materialId: "6",
            materialName: "NaCl",
            requiredQty: 10,
            availableQty: 200,
            shortage: 0,
            costPerKg: 6,
            totalCost: 60,
            unit: "kg",
          },
          {
            materialId: "1",
            materialName: "Acid Blue Color",
            requiredQty: 0.4,
            availableQty: 5,
            shortage: 0,
            costPerKg: 1680,
            totalCost: 672,
            unit: "kg",
          },
        ],
      },
    ],
    totalCost: 4430,
    totalRevenue: 7600,
    totalProfit: 3170,
    status: "scheduled",
    progress: 0,
    createdAt: "2024-01-25",
  },
];

// Status mappings for production plans
export const STATUS_CONFIG = {
  completed: {
    color: "default" as const,
    icon: CheckCircle,
  },
  "in-progress": {
    color: "default" as const,
    icon: Factory,
  },
  scheduled: {
    color: "secondary" as const,
    icon: Clock,
  },
  cancelled: {
    color: "destructive" as const,
    icon: AlertCircle,
  },
  draft: {
    color: "outline" as const,
    icon: Calendar,
  },
};

// Material inventory data (hardcoded for now, could be moved to API)
export const MATERIAL_INVENTORY = [
  {
    name: "NaCl",
    available: 200,
    required: 175,
    unit: "kg",
    cost: 6,
  },
  {
    name: "Soda Ash",
    available: 80,
    required: 110,
    unit: "kg",
    cost: 40.95,
  },
  {
    name: "Citric Acid",
    available: 60,
    required: 45,
    unit: "kg",
    cost: 97.65,
  },
  {
    name: "Caustic Soda",
    available: 25,
    required: 15,
    unit: "kg",
    cost: 59.85,
  },
  {
    name: "Ammonia",
    available: 30,
    required: 20,
    unit: "kg",
    cost: 45.0,
  },
  {
    name: "AOS Powder 96%",
    available: 45,
    required: 75,
    unit: "kg",
    cost: 152,
  },
];

export const planningAIInsights = [
  {
    type: "optimization",
    title: "Production Optimization",
    description:
      "Schedule adjustments could increase efficiency by 8% next quarter",
    impact: "High",
    confidence: 89,
  },
  {
    type: "capacity",
    title: "Capacity Planning",
    description:
      "Current capacity utilization suggests need for additional shifts",
    impact: "Medium",
    confidence: 82,
  },
  {
    type: "forecasting",
    title: "Demand Forecasting",
    description:
      "Seasonal demand patterns indicate 15% increase in Q4 production",
    impact: "High",
    confidence: 91,
  },
  {
    type: "maintenance",
    title: "Maintenance Scheduling",
    description:
      "Preventive maintenance on Line 2 could reduce downtime by 20%",
    impact: "Medium",
    confidence: 78,
  },
];
