// src/app/inventory/components/inventory-constants.ts
import { InventoryItem, InventoryTransaction } from "@/lib/types";

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "1",
    itemType: "supplierMaterial" as const,
    itemId: "6", // NaCl from supplier materials
    itemName: "Sodium Chloride",
    currentStock: 500,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 1000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "High purity salt for formulations",
    createdAt: "",
  },
  {
    id: "2",
    itemType: "supplierMaterial" as const,
    itemId: "3", // Citric Acid
    itemName: "Citric Acid",
    currentStock: 50,
    unit: "kg",
    minStockLevel: 75,
    maxStockLevel: 500,
    lastUpdated: new Date().toISOString(),
    status: "low-stock" as const,
    notes: "Used in flavor enhancement",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    itemType: "supplierPackaging" as const,
    itemId: "1", // 500ml PET Bottle
    itemName: "500ml PET Bottle",
    currentStock: 2000,
    unit: "pcs",
    minStockLevel: 500,
    maxStockLevel: 5000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Clear plastic bottles for beverages",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    itemType: "supplierLabel" as const,
    itemId: "1", // Standard Label
    itemName: "Standard Sticker Label",
    currentStock: 2100,
    unit: "pcs",
    minStockLevel: 500,
    maxStockLevel: 10000,
    lastUpdated: new Date().toISOString(),
    status: "out-of-stock" as const,
    notes: "Color printed labels for branding",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    itemType: "supplierMaterial" as const,
    itemId: "1", // supplier material id 1 (Acid Slurry)
    itemName: "Acid Slurry 90%",
    currentStock: 150,
    unit: "kg",
    minStockLevel: 50,
    maxStockLevel: 800,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Ingredient and usage information",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    itemType: "supplierMaterial" as const,
    itemId: "4", // supplier material id 4 (Acid Blue Color)
    itemName: "Acid Blue Color",
    currentStock: 800,
    unit: "kg",
    minStockLevel: 200,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Ingredient for few recipes",
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    itemType: "supplierPackaging" as const,
    itemId: "4", // spray bottle
    itemName: "250ml Spray Bottle",
    currentStock: 5000,
    unit: "pcs",
    minStockLevel: 1000,
    maxStockLevel: 20000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Generic notes for packaging",
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    itemType: "supplierPackaging" as const,
    itemId: "7", // plastic pouch
    itemName: "500g Plastic Pouch",
    currentStock: 12000,
    unit: "pcs",
    minStockLevel: 3000,
    maxStockLevel: 50000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Good packaging",
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    itemType: "supplierLabel" as const,
    itemId: "3", // supplier label id 3
    itemName: "Custom Shape Tag",
    currentStock: 2500,
    unit: "pieces",
    minStockLevel: 1000,
    maxStockLevel: 10000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Specialty Custom labels",
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    itemType: "supplierLabel" as const,
    itemId: "5", // supplier label id 5
    itemName: "Small Sticker",
    currentStock: 6000,
    unit: "pieces",
    minStockLevel: 2000,
    maxStockLevel: 20000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    notes: "Specialty small labels",
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    itemType: "supplierMaterial" as const,
    itemId: "7", // Soda Ash
    itemName: "Soda Ash",
    currentStock: 0,
    unit: "kg",
    minStockLevel: 200,
    maxStockLevel: 1500,
    lastUpdated: new Date().toISOString(),
    status: "out-of-stock" as const,
    notes: "Base material for formulations",
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    itemType: "supplierMaterial" as const,
    itemId: "10", //AOS Powder
    itemName: "AOS Powder 96%",
    currentStock: 1200,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "overstock" as const,
    notes: "Surfactant for cleaning formulations",
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: "1-init",
    inventoryItemId: "1",
    type: "in" as const,
    quantity: 500,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 500,
    createdAt: new Date().toISOString(),
    unit: "kg",
  },
  {
    id: "2-init",
    inventoryItemId: "2",
    type: "in" as const,
    quantity: 50,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 50,
    createdAt: new Date().toISOString(),
    unit: "kg",
  },
  {
    id: "3-init",
    inventoryItemId: "3",
    type: "in" as const,
    quantity: 2000,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 2000,
    createdAt: new Date().toISOString(),
    unit: "pcs",
  },
  // Additional mock transactions to demonstrate grouping
  {
    id: "4-purchase-1",
    inventoryItemId: "1",
    type: "in" as const,
    quantity: 200,
    reason: "PO #PO-1001",
    reference: "PO-1001",
    stockBefore: 300,
    stockAfter: 500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unit: "kg",
  },
  {
    id: "5-usage-1",
    inventoryItemId: "1",
    type: "out" as const,
    quantity: 50,
    reason: "Production Batch #B-201",
    reference: "B-201",
    stockBefore: 500,
    stockAfter: 450,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unit: "kg",
  },
  {
    id: "6-adjustment-1",
    inventoryItemId: "2",
    type: "adjustment" as const,
    quantity: -5,
    reason: "Manual adjustment (damaged)",
    stockBefore: 55,
    stockAfter: 50,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    unit: "kg",
  },
  {
    id: "7-purchase-2",
    inventoryItemId: "7",
    type: "in" as const,
    quantity: 5000,
    reason: "Packaging PO #PK-77",
    reference: "PK-77",
    stockBefore: 0,
    stockAfter: 5000,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    unit: "pcs",
  },
  {
    id: "8-usage-2",
    inventoryItemId: "7",
    type: "out" as const,
    quantity: 1200,
    reason: "Order Fulfilment #OF-88",
    reference: "OF-88",
    stockBefore: 5000,
    stockAfter: 3800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    unit: "pcs",
  },
  {
    id: "9-labels-1",
    inventoryItemId: "9",
    type: "in" as const,
    quantity: 2500,
    reason: "Supplier delivery",
    stockBefore: 0,
    stockAfter: 2500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    unit: "pieces",
  },
  {
    id: "10-labels-usage",
    inventoryItemId: "9",
    type: "out" as const,
    quantity: 300,
    reason: "Batch labeling",
    stockBefore: 2500,
    stockAfter: 2200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unit: "pieces",
  },
];
