// ============================================================================
// MOCK DATA FOR INVENTORY ITEMS
// ============================================================================

import { InventoryItem, InventoryTransaction } from "@/lib/types";

export const MOCK_INVENTORY_ITEMS_old: Omit<
  InventoryItem,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    itemType: "supplierMaterial",
    itemId: "6", // References SUPPLIER_MATERIALS id "6" (NaCl)
    itemName: "Sodium Chloride",
    currentStock: 500,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 1000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock",
    notes: "High purity salt for formulations",
  },
  {
    itemType: "supplierMaterial",
    itemId: "3", // References SUPPLIER_MATERIALS id "3" (Citric Acid)
    itemName: "Citric Acid",
    currentStock: 50,
    unit: "kg",
    minStockLevel: 75,
    maxStockLevel: 500,
    lastUpdated: new Date().toISOString(),
    status: "low-stock",
    notes: "Used in flavor enhancement",
  },
  {
    itemType: "supplierPackaging",
    itemId: "1", // References SUPPLIER_PACKAGING id "1" (500ml PET Bottle)
    itemName: "PET Bottle 500ml",
    currentStock: 2000,
    unit: "pcs",
    minStockLevel: 500,
    maxStockLevel: 5000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock",
    notes: "Clear plastic bottles for beverages",
  },
  {
    itemType: "supplierPackaging",
    itemId: "2", // References SUPPLIER_PACKAGING id "2" (1L Glass Jar)
    itemName: "Glass Jar 1L",
    currentStock: 100,
    unit: "pcs",
    minStockLevel: 200,
    maxStockLevel: 1000,
    lastUpdated: new Date().toISOString(),
    status: "low-stock",
    notes: "Premium glass packaging",
  },
  {
    itemType: "supplierLabel",
    itemId: "1", // References SUPPLIER_LABELS id "1" (Standard Sticker Label)
    itemName: "Front Label Sticker",
    currentStock: 5000,
    unit: "pieces",
    minStockLevel: 1000,
    maxStockLevel: 10000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock",
    notes: "Color printed labels for branding",
  },
  {
    itemType: "supplierLabel",
    itemId: "3", // References SUPPLIER_LABELS id "3" (Custom Shape Tag)
    itemName: "Back Label Tag",
    currentStock: 200,
    unit: "pieces",
    minStockLevel: 500,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "low-stock",
    notes: "Ingredient and usage information",
  },
  {
    itemType: "supplierMaterial",
    itemId: "7", // References SUPPLIER_MATERIALS id "7" (Soda Ash)
    itemName: "Soda Ash",
    currentStock: 0,
    unit: "kg",
    minStockLevel: 200,
    maxStockLevel: 1500,
    lastUpdated: new Date().toISOString(),
    status: "out-of-stock",
    notes: "Base material for formulations",
  },
  {
    itemType: "supplierPackaging",
    itemId: "6", // References SUPPLIER_PACKAGING id "6" (1kg Paper Box)
    itemName: "Cardboard Box",
    currentStock: 1500,
    unit: "pcs",
    minStockLevel: 300,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock",
    notes: "Secondary packaging",
  },
  {
    itemType: "supplierLabel",
    itemId: "2", // References SUPPLIER_LABELS id "2" (Premium Label Tag)
    itemName: "Foil Label",
    currentStock: 800,
    unit: "sheets",
    minStockLevel: 400,
    maxStockLevel: 1500,
    lastUpdated: new Date().toISOString(),
    status: "in-stock",
    notes: "Specialty metallic labels",
  },
  {
    itemType: "supplierMaterial",
    itemId: "10", // References SUPPLIER_MATERIALS id "10" (AOS Powder 96%)
    itemName: "AOS Powder 96%",
    currentStock: 1200,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "overstock",
    notes: "Surfactant for cleaning formulations",
  },
];

export const MOCK_INVENTORY_ITEMS = [
  {
    id: "1",
    itemType: "supplierMaterial" as const,
    itemId: "6", // NaCl from supplier materials
    itemName: "",
    currentStock: 500,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 1000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    itemType: "supplierMaterial" as const,
    itemId: "3", // Citric Acid
    itemName: "",
    currentStock: 50,
    unit: "kg",
    minStockLevel: 75,
    maxStockLevel: 500,
    lastUpdated: new Date().toISOString(),
    status: "low-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    itemType: "supplierPackaging" as const,
    itemId: "1", // 500ml PET Bottle
    itemName: "",
    currentStock: 2000,
    unit: "pcs",
    minStockLevel: 500,
    maxStockLevel: 5000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    itemType: "supplierLabel" as const,
    itemId: "1", // Standard Label
    itemName: "",
    currentStock: 2100,
    unit: "pcs",
    minStockLevel: 500,
    maxStockLevel: 10000,
    lastUpdated: new Date().toISOString(),
    status: "out-of-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    itemType: "supplierMaterial" as const,
    itemId: "1", // supplier material id 1 (Acid Slurry)
    itemName: "",
    currentStock: 150,
    unit: "kg",
    minStockLevel: 50,
    maxStockLevel: 800,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    itemType: "supplierMaterial" as const,
    itemId: "4", // supplier material id 4 (Caustic Soda)
    itemName: "",
    currentStock: 800,
    unit: "kg",
    minStockLevel: 200,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    itemType: "supplierPackaging" as const,
    itemId: "4", // spray bottle
    itemName: "",
    currentStock: 5000,
    unit: "pcs",
    minStockLevel: 1000,
    maxStockLevel: 20000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    itemType: "supplierPackaging" as const,
    itemId: "7", // plastic pouch
    itemName: "",
    currentStock: 12000,
    unit: "pcs",
    minStockLevel: 3000,
    maxStockLevel: 50000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    itemType: "supplierLabel" as const,
    itemId: "3", // supplier label id 3
    itemName: "",
    currentStock: 2500,
    unit: "pieces",
    minStockLevel: 1000,
    maxStockLevel: 10000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    itemType: "supplierLabel" as const,
    itemId: "5", // supplier label id 5
    itemName: "",
    currentStock: 6000,
    unit: "pieces",
    minStockLevel: 2000,
    maxStockLevel: 20000,
    lastUpdated: new Date().toISOString(),
    status: "in-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    itemType: "supplierMaterial" as const,
    itemId: "7", // Soda Ash
    itemName: "",
    currentStock: 0,
    unit: "kg",
    minStockLevel: 200,
    maxStockLevel: 1500,
    lastUpdated: new Date().toISOString(),
    status: "out-of-stock" as const,
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    itemType: "supplierMaterial" as const,
    itemId: "10", // AOS Powder
    itemName: "",
    currentStock: 1200,
    unit: "kg",
    minStockLevel: 100,
    maxStockLevel: 2000,
    lastUpdated: new Date().toISOString(),
    status: "overstock" as const,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: "1-init",
    inventoryItemId: "1",
    type: "in" as const,
    quantity: 500,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 500,
    createdAt: new Date().toISOString(),
    unit: "kg",
  },
  {
    id: "2-init",
    inventoryItemId: "2",
    type: "in" as const,
    quantity: 50,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 50,
    createdAt: new Date().toISOString(),
    unit: "kg",
  },
  {
    id: "3-init",
    inventoryItemId: "3",
    type: "in" as const,
    quantity: 2000,
    reason: "Initial Stock",
    stockBefore: 0,
    stockAfter: 2000,
    createdAt: new Date().toISOString(),
    unit: "pcs",
  },
  // Additional mock transactions to demonstrate grouping
  {
    id: "4-purchase-1",
    inventoryItemId: "1",
    type: "in" as const,
    quantity: 200,
    reason: "PO #PO-1001",
    reference: "PO-1001",
    stockBefore: 300,
    stockAfter: 500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unit: "kg",
  },
  {
    id: "5-usage-1",
    inventoryItemId: "1",
    type: "out" as const,
    quantity: 50,
    reason: "Production Batch #B-201",
    reference: "B-201",
    stockBefore: 500,
    stockAfter: 450,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unit: "kg",
  },
  {
    id: "6-adjustment-1",
    inventoryItemId: "2",
    type: "adjustment" as const,
    quantity: -5,
    reason: "Manual adjustment (damaged)",
    stockBefore: 55,
    stockAfter: 50,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    unit: "kg",
  },
  {
    id: "7-purchase-2",
    inventoryItemId: "7",
    type: "in" as const,
    quantity: 5000,
    reason: "Packaging PO #PK-77",
    reference: "PK-77",
    stockBefore: 0,
    stockAfter: 5000,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    unit: "pcs",
  },
  {
    id: "8-usage-2",
    inventoryItemId: "7",
    type: "out" as const,
    quantity: 1200,
    reason: "Order Fulfilment #OF-88",
    reference: "OF-88",
    stockBefore: 5000,
    stockAfter: 3800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    unit: "pcs",
  },
  {
    id: "9-labels-1",
    inventoryItemId: "9",
    type: "in" as const,
    quantity: 2500,
    reason: "Supplier delivery",
    stockBefore: 0,
    stockAfter: 2500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    unit: "pieces",
  },
  {
    id: "10-labels-usage",
    inventoryItemId: "9",
    type: "out" as const,
    quantity: 300,
    reason: "Batch labeling",
    stockBefore: 2500,
    stockAfter: 2200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unit: "pieces",
  },
];
